ecosystem:
  main_project: optaplanner
  projects:
  - name: optaplanner
    regexs:
    - incubator-kie-opta.*
    - opta.*
  - name: kie-benchmarks
    ignore_release: true
    regexs:
    - incubator-kie-benchmarks.*
git:
  branches:
  - name: push-privilege
    main_branch: true
seed:
  config_file:
    git:
      repository: optaplanner
      author:
        name: jstastny-cz
        credentials_id: ASF_Cloudbees_Jenkins_ci-builds
      branch: push-privilege
    path: .ci/jenkins/config/branch.yaml
jenkins:
  email_creds_id: OPTAPLANNER_CI_NOTIFICATION_EMAILS
